name: Code tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    env:
      SANIC_FORUM_ENVIRONMENT: 'testing'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: pip install -e ".[test]"

    - name: Run tests
      run: pytest tests
